apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-07-10T07:14:17Z"
  generateName: frontend-5c787d75cf-
  labels:
    app: frontend
    pod-template-hash: 5c787d75cf
  name: frontend-5c787d75cf-7dhwt
  namespace: ai-career-chat
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: frontend-5c787d75cf
    uid: dcfb4db7-011c-4dff-bbd2-b8e4297a3a97
  resourceVersion: "1752131851806511019"
  uid: e909d22b-9fa5-4f29-8c0e-abdc4262f39d
spec:
  containers:
  - env:
    - name: REACT_APP_API_URL
      value: /api
    - name: REACT_APP_AI_URL
      value: /api
    image: gcr.io/plenary-ridge-464412-k5/frontend
    imagePullPolicy: Always
    name: frontend
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bgn7c
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-ai-career-chat-bot-c-default-pool-ba40f247-v3qv
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-bgn7c
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T07:14:21Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T07:14:17Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T07:17:16Z"
    message: 'containers with unready status: [frontend]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T07:17:16Z"
    message: 'containers with unready status: [frontend]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T07:14:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://249e340ba4200036dbcf317568bd8ce9c5ac9bc2d14f7e1812b3be124d43f7bb
    image: gcr.io/plenary-ridge-464412-k5/frontend:latest
    imageID: gcr.io/plenary-ridge-464412-k5/frontend@sha256:854c5a616ac92359af00e258e702e2cee899a5acdb8b5c323215610ab77c88f8
    lastState:
      terminated:
        containerID: containerd://249e340ba4200036dbcf317568bd8ce9c5ac9bc2d14f7e1812b3be124d43f7bb
        exitCode: 1
        finishedAt: "2025-07-10T07:17:15Z"
        reason: Error
        startedAt: "2025-07-10T07:17:15Z"
    name: frontend
    ready: false
    restartCount: 5
    started: false
    state:
      waiting:
        message: back-off 2m40s restarting failed container=frontend pod=frontend-5c787d75cf-7dhwt_ai-career-chat(e909d22b-9fa5-4f29-8c0e-abdc4262f39d)
        reason: CrashLoopBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bgn7c
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.128.0.10
  hostIPs:
  - ip: 10.128.0.10
  phase: Running
  podIP: 10.24.1.6
  podIPs:
  - ip: 10.24.1.6
  qosClass: Burstable
  startTime: "2025-07-10T07:14:17Z"
