apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ai-career-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/plenary-ridge-464412-k5/backend
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATA_REDIS_HOST
              value: redis-service
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://svc.sel5.cloudtype.app:31061/careerManager?serverTimezone=Asia/Seoul&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATA_REDIS_CLIENT_SSL_ENABLED
              value: "false"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"