apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langchain-uploads-pvc
  namespace: ai-career-chat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard