apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: ai-career-chat
  labels:
    app: langchain
stringData:
  OPENAI_API_KEY: "c2stcHJvai1iOVdNdFJteHZuOG5HRXotc3RHZXhDZ0VoZV9yZ3IxdGUycEU3RjgwMjZvbnZsT1ktcjY1eEFObnNITTRHSnRvZmZEbFFIbU1mcFQzQmxia0ZKSGdLdG9CUEtDU3VpdmU2N0JpT0ZVNXlaSFNnaE1PMXpHNlJnbF9EMHVDTVBoS0NTZl9oVnFMVEFXcVVjZUMxdWNEeXRNX3prQQ=="

type: Opaque