apiVersion: v1
kind: Service
metadata:
  name: langchain-service
  namespace: ai-career-chat
spec:
  selector:
    app: langchain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP